quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=maicols1230
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/studycards

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.http.cors=true
quarkus.http.cors.origins=/.*/